#!/usr/bin/env -S python3 -u

import argparse
import json
import select
import socket


class Router:
    relations = {}
    sockets = {}
    ports = {}  # Dictionary to identify the port associated to each IP

    table_disaggregated = {}  # Table that contains all the updates, no aggregation applied
    table_aggregation = {}  # Table that contains all the updates, no aggregation applied
    ports_original = {}  # Dictionary to identify the IP associated to each port

    def __init__(self, asn, connections):
        print("Router at AS %s starting up" % asn)
        self.asn = asn
        for relationship in connections:
            # Neighbor == IP that ends with .2
            port, neighbor, relation = relationship.split("-")

            self.sockets[neighbor] = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sockets[neighbor].bind(('localhost', 0))

            self.ports[neighbor] = int(port)
            self.ports_original[int(port)] = neighbor

            self.relations[neighbor] = relation
            self.send(neighbor,
                      json.dumps({"type": "handshake", "src": self.our_addr(neighbor), "dst": neighbor, "msg": {}}))

            self.table_disaggregated[int(port)] = []
            self.table_aggregation[int(port)] = []

    def our_addr(self, dst):
        """Router IP address, takes the destination and changes the final 2 with a 1"""
        quads = list(int(qdn) for qdn in dst.split('.'))
        quads[3] = 1
        return "%d.%d.%d.%d" % (quads[0], quads[1], quads[2], quads[3])

    def send(self, network, message):
        """Sends message to given network"""
        self.sockets[network].sendto(message.encode('utf-8'), ('localhost', self.ports[network]))

    def update(self, msg_dic):
        """Updates both aggregated and disaggregated routing tables by adding the new received message"""
        msg_dic_copy = msg_dic.copy()
        msg_dic_copy['msg'] = msg_dic['msg'].copy()

        # Update disaggregated forwarding table
        port = self.ports[msg_dic['src']]  # Get the port from which we received the message

        self.table_disaggregated[port].append(msg_dic['msg'])  # Add the update with the port as the key
        self.table_disaggregated[port][-1]['peer'] = msg_dic['src']  # Add peer information to the entry

        # Send copies of the announcement
        self.update_neighbors(msg_dic, "update", {
            "network": msg_dic['msg']['network'],
            "netmask": msg_dic['msg']['netmask'],
            "ASPath": [self.asn] + msg_dic['msg']['ASPath']
        })

        # Updated aggregated forwarding table
        self.table_aggregation[port].append(msg_dic_copy['msg'])  # Add the update with the port as the key
        # Add extra information to the entry
        self.table_aggregation[port][-1]['peer'] = msg_dic_copy['src']
        # This will be used leter to check if we should disasggregate the forwarding table
        self.table_aggregation[port][-1]['aggregated'] = False

        # Check if we should apply aggregation
        self.check_aggregation_after_update(port)

    def check_aggregation_after_update(self, port):
        """Goes over all entries in the aggregated table to see if new aggregation can be performed"""
        # check if the last added network can be aggregated
        i = 0
        while i < len(self.table_aggregation[port]) - 1:
            network = self.table_aggregation[port][i]
            if self.is_aggregable(port, network, self.table_aggregation[port][-1]):
                # if we had performed aggregation, we must check everything again
                i = 0
            else:
                i += 1

    def check_aggregation_after_withdraw(self, port):
        """Goes over all entries in the aggregated table to re-aggregate after a withdrawal"""
        i = 0
        while i < len(self.table_aggregation[port]):
            j = i + 1
            while j < len(self.table_aggregation[port]):
                if self.is_aggregable(port, self.table_aggregation[port][i], self.table_aggregation[port][j]):
                    # If we had performed aggregation, we must check everything again
                    i = -1
                    j = len(self.table_aggregation[port])
                else:
                    j += 1

            i += 1

    def is_aggregable(self, port, network1, network2):
        """Checks if both IPs can be aggregated, and performs the aggregation if possible"""
        if network1['localpref'] == network2['localpref'] \
                and network1['selfOrigin'] == network2['selfOrigin'] \
                and network1['origin'] == network2['origin'] \
                and network1['netmask'] == network2['netmask']:

            # Check if the networks coincide
            # Both netmasks are equal, I can use either of them
            binary_netmask = self.ip_to_binary(network1['netmask'])

            long = 31
            while long > 0 and binary_netmask[long] == '0':
                long -= 1

            # Now 'long' contains the position of the first '1' of the netwask which is the position of the first bit
                # we don't want to compare

            # Convert both networks to binary
            binary_network1 = self.ip_to_binary(network1['network'])[0:long]
            binary_network2 = self.ip_to_binary(network2['network'])[0:long]

            if binary_network1 == binary_network2:
                # Delete the original network (because of aggregation)
                # By keeping the new one at the end, we can run the same algorithm again (for the update case)
                self.table_aggregation[port].remove(network1)

                # Update the aggregated entry
                # Update netmask
                aux = list(binary_netmask)
                aux[long] = '0'
                binary_netmask = ''.join(aux)
                aux = [int(binary_netmask[i:i + 8], 2) for i in range(0, 25, 8)]

                network2['netmask'] = "%d.%d.%d.%d" % (aux[0], aux[1], aux[2], aux[3])

                # Update network
                binary_network = self.ip_to_binary(network2['network'])

                aux = list(binary_network)
                aux[long] = '0'
                binary_network = ''.join(aux)
                aux = [int(binary_network[i:i + 8], 2) for i in range(0, 25, 8)]

                network2['network'] = "%d.%d.%d.%d" % (aux[0], aux[1], aux[2], aux[3])
                network2['aggregated'] = True
                return True

        return False

    def ip_to_binary(self, ip):
        """Convert the given netowrk to binary"""
        aux = ip.split('.')
        binary_number = ""
        for i in aux:
            binary = format(int(i), "08b")
            binary_number += str(binary)
        return binary_number

    def search_port(self, ip):
        """Search to what port that IP is connected"""
        port = -1
        ip_split = ip.split('.')

        i = 0
        ports_list = list(self.table_aggregation.keys())
        flag = False
        while not flag and i < len(ports_list):
            networks_of_port_list = self.table_aggregation[ports_list[i]]
            j = 0
            while not flag and j < len(networks_of_port_list):
                # Apply the mask
                current_netmask = networks_of_port_list[j]['netmask'].split('.')
                dest_masked = [int(ip_split[index]) & int(current_netmask[index]) for index in range(4)]
                src_masked = [int(networks_of_port_list[j]['network'].split('.')[index]) & int(current_netmask[index])
                              for index in range(4)]
                # Compare with the given network
                k = 0
                flag = True
                # For each number of the IP, compare if they are the same to see if they are connected
                while flag and k < 4:
                    if dest_masked[k] != src_masked[k]:
                        flag = False
                    k += 1

                if flag:
                    # If flag did not become False, it means we found the port ('i' contains the current port)
                    port = ports_list[i]

                j += 1
            i += 1

        return port  # -1 if the port is not found

    def search_networks(self, ip):
        """Find destiination IP """
        network_matches = []  # List of all the networks that match the ip
        ip_split = ip.split('.')

        i = 0
        ports_list = list(self.table_aggregation.keys())
        while i < len(ports_list):
            networks_of_port_list = self.table_aggregation[ports_list[i]]
            j = 0
            while j < len(networks_of_port_list):
                # Apply the mask
                current_netmask = networks_of_port_list[j]['netmask'].split('.')
                dest_masked = [int(ip_split[index]) & int(current_netmask[index]) for index in range(4)]
                src_masked = [int(networks_of_port_list[j]['network'].split('.')[index]) & int(current_netmask[index])
                              for index in range(4)]
                # Compare with the given network
                k = 0
                flag = True
                # Solo dejar la flag aqui y en los demas siempre correrlo, entonces al final coger
                # el que mas largo tenga parecido
                while flag and k < 4:
                    if dest_masked[k] != src_masked[k]:
                        flag = False
                    k += 1

                if flag:
                    network_matches.append(networks_of_port_list[j])
                j += 1
            i += 1

        return network_matches

    def data_send(self, ip, type_msg, src, dst, msg):
        """Check if we can send the data based on their relationship"""
        if ip is None:
            self.send(dst, json.dumps({"type": type_msg, "src": src, "dst": dst, "msg": msg}))
        elif self.relations[self.ports_original[self.search_port(src)]] == 'cust' or self.relations[ip] == 'cust':
            self.send(ip, json.dumps({"type": type_msg, "src": src, "dst": dst, "msg": msg}))
        else:
            # Search the port that contains the source, to send the message back
            src_port = self.search_port(src)
            src = self.our_addr(self.ports_original[src_port])

            self.send(self.ports_original[src_port],
                      json.dumps({"type": "no route", "src": src, "dst": dst, "msg": {}}))

    def data(self, msg_dic):
        """Check if there is a route and where to send the received data"""
        # Get the port associated with the IP of the destination
        dest_networks = self.search_networks(msg_dic['dst'])

        # Easy case: no route
        # -----------
        if len(dest_networks) == 0:  # port not found
            dst = self.ports_original[self.search_port(msg_dic['src'])]
            self.data_send(None, "no route", self.our_addr(dst), dst, {})

        # Easy case: one destination found
        # -----------
        elif len(dest_networks) == 1:  # port found
            # forward the original message to the right destination
            self.data_send(dest_networks[0]['peer'],
                           "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])

        # Other case: choose the best "matching" network
        # -----------
        else:
            # First: get the longest subnet mask
            networks_longest_prefix = []

            maxim = 0
            for network in dest_networks:
                a = int(network['network'].replace('.', ''))
                if a > maxim:
                    networks_longest_prefix = [network]
                    maxim = a
                elif a == maxim:
                    networks_longest_prefix.append(network)

            if len(networks_longest_prefix) == 1:
                # forward the original message to the right destination
                self.data_send(networks_longest_prefix[0]['peer'],
                               "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])

            else:  # Tie in the longest prefix
                # 1st: check the highest local pref
                networks_highest_pref = []
                maxim = 0
                for network in networks_longest_prefix:

                    a = network['localpref']
                    if a > maxim:
                        networks_highest_pref = [network]
                        maxim = a
                    elif a == maxim:
                        networks_highest_pref.append(network)

                if len(networks_highest_pref) == 1:
                    # Forward the original message to the right destination
                    self.data_send(networks_highest_pref[0]['peer'],
                                   "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])

                else:
                    # 2nd: check selfOrigin
                    networks_selforigin = networks_highest_pref
                    for network in networks_selforigin:
                        if not network['selfOrigin']:
                            networks_selforigin.remove(network)

                    # In case all networks have selfOrigin = False restore the original list
                    if len(networks_selforigin) == 0:
                        networks_selforigin = networks_highest_pref

                    if len(networks_selforigin) == 1:
                        self.data_send(networks_selforigin[0]['peer'],
                                       "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])

                    else:
                        # 3rd: check ASpath
                        networks_shortest_ASPath = []
                        minim = len(networks_selforigin[0]['ASPath'])
                        for network in networks_selforigin:
                            a = len(network['ASPath'])
                            if a < minim:
                                networks_shortest_ASPath = [network]
                                minim = a
                            elif a == minim:
                                networks_shortest_ASPath.append(network)

                        if len(networks_shortest_ASPath) == 1:
                            self.data_send(networks_shortest_ASPath[0]['peer'],
                                           "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])
                        else:
                            # 4th: check origin
                            igp, egp, unk = [], [], []
                            for network in networks_shortest_ASPath:
                                if network['origin'] == 'IGP':
                                    igp.append(network)
                                elif network['origin'] == 'EGP':
                                    egp.append(network)
                                else:
                                    unk.append(network)

                            if len(igp) == 0 and len(egp) == 0:
                                final_candidates = unk
                            elif len(igp) == 0:
                                final_candidates = egp
                            else:
                                final_candidates = igp

                            if len(final_candidates) == 1:
                                self.data_send(final_candidates[0]['peer'],
                                               "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])
                            else:
                                #  5th: check src
                                networks_lowest_src = []
                                mini = int(final_candidates[0]['peer'].replace('.', ''))
                                for network in final_candidates:
                                    a = int(network['peer'].replace('.', ''))
                                    if a < mini:
                                        networks_lowest_src = [network]
                                        mini = a
                                    elif a == mini:
                                        networks_lowest_src.append(network)

                                # The problem statement ensures that there will be no ties at this point
                                self.data_send(networks_lowest_src[0]['peer'],
                                               "data", msg_dic['src'], msg_dic['dst'], msg_dic['msg'])

    def dump(self, dst):
        """Send the current forwarding table to the source requesting it"""
        self.send(dst,
                  json.dumps({"type": "table",
                              "src": self.our_addr(dst),
                              "dst": dst,
                              "msg": [self.show_fields(x) for sublist in self.table_aggregation.values() for x in sublist]}))
        # We need to forward a list just with the networks dictionary

    def show_fields(self, x):
        """Just return the necessary fields when dumping"""
        return {
            "network": x['network'],
            "netmask": x["netmask"],
            "localpref": x['localpref'],
            "selfOrigin": x['selfOrigin'],
            "ASPath": x['ASPath'],
            "origin": x['origin'],
            "peer": x['peer']
        }

    def withdraw(self, msg_dic):
        """Deletes a connection from a router to a specific netowork"""
        # Delete the network in the disaggregated forwarding table
        for net_from_table in self.table_disaggregated[self.ports[msg_dic['src']]]:
            for net_withdraw in msg_dic['msg']:
                if net_from_table['network'] == net_withdraw['network'] \
                        and net_from_table['netmask'] == net_withdraw['netmask']:
                    self.table_disaggregated[self.ports[msg_dic['src']]].remove(net_from_table)

        # Delete the network in the disaggregated forwarding table
        for net_from_table in self.table_aggregation[self.ports[msg_dic['src']]]:
            for net_withdraw in msg_dic['msg']:
                # Compare the two networks applying the mask of net_from_table (it's the lowest one)
                # We don't need to apply the mask to net_withdraw because we save the network already masked
                current_netmask = net_from_table['netmask'].split('.')
                aux = [int(net_withdraw['network'].split('.')[index]) & int(current_netmask[index]) for index in
                       range(4)]

                net_withdraw_masked = "%d.%d.%d.%d" % (aux[0], aux[1], aux[2], aux[3])

                if net_withdraw_masked == net_from_table['network']:
                    if not net_from_table['aggregated']:
                        self.table_aggregation[self.ports[msg_dic['src']]].remove(net_from_table)
                    else:
                        # If an aggregation has been performed, restore the table with the non aggregated copy
                        self.table_aggregation[self.ports[msg_dic['src']]] = self.copy_networks(
                            self.table_disaggregated[self.ports[msg_dic['src']]])

                        self.check_aggregation_after_withdraw(self.ports[msg_dic['src']])

        # Update neighbors about the withdram
        self.update_neighbors(msg_dic, "withdraw", msg_dic['msg'])

    def copy_networks(self, list_original):
        """Copy the networks dictionary so the orignal does not get modified"""
        copied_list = []
        for dict in list_original:
            copied_list.append(dict.copy())

        return copied_list

    def update_neighbors(self, msg_dic, type, msg):
        """For each network accesible through that router, send the messgae to them only if they are both customers"""
        for ip in self.relations:
            if ip != msg_dic['src']:  # Not updating the neighbor that has sent me the update
                # Updating the neighbours depends on the relations
                if self.relations[msg_dic['src']] == 'cust' or self.relations[ip] == 'cust':
                    self.send(ip,
                              json.dumps({"type": type,
                                          "src": self.our_addr(ip),
                                          "dst": ip,
                                          "msg": msg}))

    def run(self):
        """Run the router and do what the message said"""
        while True:
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                k, addr = conn.recvfrom(65535)  # k == message, addr == address where it gets it from
                srcif = None
                for sock in self.sockets:
                    if self.sockets[sock] == conn:
                        srcif = sock
                        break
                msg = k.decode('utf-8')

                msg_dic = json.loads(msg)  # msg is now a python dictionary

                if msg_dic["type"] == "update":
                    self.update(msg_dic)

                elif msg_dic["type"] == "data":
                    self.data(msg_dic)

                elif msg_dic["type"] == "dump":
                    self.dump(msg_dic['src'])

                elif msg_dic["type"] == "withdraw":
                    self.withdraw(msg_dic)

                else:
                    print("Operation", msg_dic["type"], "not implemented yet")

                print("Received message '%s' from %s" % (msg, srcif))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='route packets')
    parser.add_argument('asn', type=int, help="AS number of this router")
    parser.add_argument('connections', metavar='connections', type=str, nargs='+', help="connections")
    args = parser.parse_args()
    router = Router(args.asn, args.connections)
    router.run()
